### PR TITLE
Add description field to upgrade command

### PR DESCRIPTION
**Pull request by dariacherniakk**

### CODE REVIEW

**Comment by cloudmex-alan** [comment]
@dariacherniakk can you provide a loom video of this PR working? In order to accept it.

**Comment by dariacherniakk** [comment]
> @dariacherniakk can you provide a loom video of this PR working? In order to accept it. Thanks!

Sure

**Comment by dariacherniakk** [comment]
> @dariacherniakk can you provide a loom video of this PR working? In order to accept it. Thanks!

https://app.videoform.com/share/BWtJtpPn67on5hUG?fname=description_for_upgrade

**Comment by dariacherniakk** [comment]
@cloudmex-alan Hello! Share the link with you above

**Pull request merged**
